### ISSUE TITLE
Unfriendly error 500 when env name is unknown by comfy

### ISSUE THREAD

**Issue by JulienMattiussi** [marmelab/comfygure#137]
### Description

If I try to get for a non existant environment on comfy, then I get a 500 error.

### Steps to Reproduce

1. type "comfy get fake_env"
2. Get this error message:

```
The API call returned a 500 HTTP error code
Error: The API call returned a 500 HTTP error code
    at Request._callback (/home/julienm/.nvm/versions/node/v8.10.0/lib/node_modules/comfygure/src/client.js:14:27)
    at Request.self.callback (/home/julienm/.nvm/versions/node/v8.10.0/lib/node_modules/comfygure/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/julienm/.nvm/versions/node/v8.10.0/lib/node_modules/comfygure/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/julienm/.nvm/versions/node/v8.10.0/lib/node_modules/comfygure/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
Unknown error, command aborted.
If the error persists, please report it at https://github.com/marmelab/comfygure/issues
```

I would be so much better to have an explicit message like

`Cannot get env "fake_env", check existing env with "comfy env list"`

- Exact date when the issue happened: 26/03/2019

**Comment by JulienMattiussi** [comment]
Issue fixed in 0.1.3
:+1:
